#! /bin/bash

python cdag_info_theoretic_search.py --dataset=3var --random_seed=42 --n_clusters 2
python cdag_info_theoretic_search.py --dataset=4var --random_seed=42 --n_clusters 2
python cdag_info_theoretic_search.py --dataset=7var --random_seed=42 --n_clusters 3
