#! /bin/bash

DIR=$(date +"%Y-%m-%d-%T")

CUDA_VISIBLE_DEVICES='0'

mkdir -p results/$DIR/bayesian/sachs
mkdir -p results/$DIR/bayesian/housing

N_DATA_SAMPLES=1000
N_MCMC_SAMPLES=2000
N_MCMC_WARMUP=500
MAX_EM_ITERS=8
MAX_MLE_ITERS=1000
NUM_CHAINS=10

python run_experiment.py \
    --n_data_samples $N_DATA_SAMPLES \
    --n_mcmc_samples $N_MCMC_SAMPLES \
    --n_mcmc_warmup $N_MCMC_WARMUP \
    --max_em_iters $MAX_EM_ITERS \
    --max_mle_iters $MAX_MLE_ITERS \
    --min_clusters 3 \
    --max_clusters 3 \
    --num_chains $NUM_CHAINS \
    --dataset 'sachs' \
    --output_path results/$DIR/bayesian/sachs

python run_experiment.py \
    --n_data_samples $N_DATA_SAMPLES \
    --n_mcmc_samples $N_MCMC_SAMPLES \
    --n_mcmc_warmup $N_MCMC_WARMUP \
    --max_em_iters $MAX_EM_ITERS \
    --max_mle_iters $MAX_MLE_ITERS \
    --min_clusters 9 \
    --max_clusters 9 \
    --num_chains $NUM_CHAINS \
    --dataset 'housing' \
    --output_path results/$DIR/bayesian/housing
