#! /bin/bash

DIR=$(date +"%Y-%m-%d-%T")
mkdir -p results/$DIR

N_DATA_SAMPLES=1000
N_MCMC_SAMPLES=500
N_MCMC_WARMUP=100
MAX_EM_ITERS=20
MAX_MLE_ITERS=500

python run_experiment.py \
    --data continuous_5 \
    --n_data_samples $N_DATA_SAMPLES \
    --n_mcmc_samples $N_MCMC_SAMPLES \
    --n_mcmc_warmup $N_MCMC_WARMUP \
    --max_em_iters $MAX_EM_ITERS \
    --max_mle_iters $MAX_MLE_ITERS \
    --output_path results/$DIR
