#! /bin/bash

CUDA_VISIBLE_DEVICES='0'

python cdag_info_theoretic_search.py --dataset=3var --random_seed=42 --n_clusters=2 --n_runs=20 --n_iters=500 --n_data_samples=1000
python cdag_info_theoretic_search.py --dataset=4var --random_seed=42 --n_clusters=2 --n_runs=20 --n_iters=500 --n_data_samples=1000
python cdag_info_theoretic_search.py --dataset=7var --random_seed=42 --n_clusters=3 --n_runs=20 --n_iters=500 --n_data_samples=1000
python cdag_info_theoretic_search.py --dataset=sachs --random_seed=42 --n_clusters=3 --n_runs=20 --n_iters=500 --n_data_samples=1000
python cdag_info_theoretic_search.py --dataset=housing --random_seed=42 --n_clusters=9 --n_runs=20 --n_iters=500 --n_data_samples=1000
